
site:
  name: Ticsta
  title: Static Website Platform
  host: www.ticsta.com

defaultSection: pages

###  VARIABLES
# name - document name
# slug - document slug
# title - slug, name
# section - document section
# type - document type
### group_GROUPNAME - example: group_tags or group_categories
# year - document 4 year
# month - 01..12
# i_month - 1..12
# day - 01..31
# i_day - 1..31
# short_year - 2014 > 14
# extension - file extension
# unique_name - groupItem uniqueName (ex: categories:politics, tags:new-york)
# page - currentPage in pagger
###
permalink:
  simple: :section/:title.:extension


assets:
  names:
    css-main:
      - static/css/white.min.css
    js-main:
      - static/js/main.min.js